# Generated by Django 3.1 on 2020-08-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmazonShipmentID', models.TextField(blank=True, max_length=1000, null=True)),
                ('CompanyName', models.TextField(blank=True, max_length=10000, null=True)),
                ('CreatedDate', models.TextField(blank=True, max_length=10000, null=True)),
                ('PRONumber', models.TextField(blank=True, max_length=10000, null=True)),
                ('ShipStatus', models.TextField(blank=True, max_length=10000, null=True)),
                ('ShipStatusNum', models.IntegerField(blank=True, null=True)),
                ('TotalCartons', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
